--- #YAML:1.0
name:               Parse-Debian-PackageDesc
version:            0.15
abstract:           Parses Debian changes and source package files
author:
    - Esteban Manchado Velázquez <estebanm@opera.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Deep:  0.093
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
